# -*- coding: utf-8 -*-
"""Updated_of_coding_TA_covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6-bSH6cCQ5DZbkW6daFQMbaH3jTwv2K

# Preprocessing dataset
"""

# import library
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import scipy as sp

# upload dataset
from google.colab import files
uploaded = files.upload()

Bihbul = pd.read_excel('dataset AQI Bihbul.xlsx')
Bihbul = Bihbul.iloc[:,0:5]

Bojongsoang = pd.read_excel('dataset AQI Bojongsoang.xlsx')
Bojongsoang = Bojongsoang.iloc[:,0:5]

Cibeunying = pd.read_excel('dataset AQI Cibeunying.xlsx')
Cibeunying = Cibeunying.iloc[:,0:5]

Cinunuk = pd.read_excel('dataset AQI Cinunuk.xlsx')
Cinunuk = Cinunuk.iloc[:,0:5]

Jelekong = pd.read_excel('dataset AQI Jelekong.xlsx')
Jelekong = Jelekong.iloc[:,0:5]

Rahayu = pd.read_excel('dataset AQI Rahayu.xlsx')
Rahayu = Rahayu.iloc[:,0:5]

AQI = pd.merge(Bihbul,Bojongsoang,on='time')

AQI = pd.merge(AQI,Cibeunying,on='time')

AQI = pd.merge(AQI,Cinunuk,on='time')

AQI = pd.merge(AQI,Jelekong,on='time')

AQI = pd.merge(AQI,Rahayu,on='time')

AQI

AQI = AQI.drop(['time','KETERANGAN PM10 Bihbul','KETERANGAN PM2.5 Bihbul','KETERANGAN PM10 Bojongsoang','KETERANGAN PM2.5 Bojongsoang','KETERANGAN PM10 Cibeunying','KETERANGAN PM2.5 Cibeunying','KETERANGAN PM10 Cinunuk','KETERANGAN PM2.5 Cinunuk','KETERANGAN PM10 Jelekong','KETERANGAN PM2.5 Jelekong','KETERANGAN PM10 Rahayu','KETERANGAN PM2.5 Rahayu'],axis=1)
print(AQI)

label_mapping = {'Baik': 2, 'Sedang': 1, 'Tidak Sehat': 0}
AQI['KETERANGAN PM10 Bihbul'] = AQI['KETERANGAN PM10 Bihbul'].map(label_mapping)
AQI['KETERANGAN PM2.5 Bihbul'] = AQI['KETERANGAN PM2.5 Bihbul'].map(label_mapping)
AQI['KETERANGAN PM10 Bojongsoang'] = AQI['KETERANGAN PM10 Bojongsoang'].map(label_mapping)
AQI['KETERANGAN PM2.5 Bojongsoang'] = AQI['KETERANGAN PM2.5 Bojongsoang'].map(label_mapping)
AQI['KETERANGAN PM10 Cibeunying'] = AQI['KETERANGAN PM10 Cibeunying'].map(label_mapping)
AQI['KETERANGAN PM2.5 Cibeunying'] = AQI['KETERANGAN PM2.5 Cibeunying'].map(label_mapping)
AQI['KETERANGAN PM10 Cinunuk'] = AQI['KETERANGAN PM10 Cinunuk'].map(label_mapping)
AQI['KETERANGAN PM2.5 Cinunuk'] = AQI['KETERANGAN PM2.5 Cinunuk'].map(label_mapping)
AQI['KETERANGAN PM10 Jelekong'] = AQI['KETERANGAN PM10 Jelekong'].map(label_mapping)
AQI['KETERANGAN PM2.5 Jelekong'] = AQI['KETERANGAN PM2.5 Jelekong'].map(label_mapping)
AQI['KETERANGAN PM10 Rahayu'] = AQI['KETERANGAN PM10 Rahayu'].map(label_mapping)
AQI['KETERANGAN PM2.5 Rahayu'] = AQI['KETERANGAN PM2.5 Rahayu'].map(label_mapping)

# read dataset
covid = pd.read_excel('dataset puskesmas.xlsx')
print(covid)

# filter status covid Rendah
covid_filtered = covid[covid['STATUS COVID'] == "RENDAH"]
print(covid_filtered)

# filter status covid Sedang
covid_filtered = covid[covid['STATUS COVID'] == "SEDANG"]
print(covid_filtered)

# filter status covid Tinggi
covid_filtered = covid[covid['STATUS COVID'] == "TINGGI"]
print(covid_filtered)

# Comparison plot status sovid Tinggi dan Rendah
covidOrno = [np.count_nonzero(covid['STATUS COVID'] == 'RENDAH'), np.count_nonzero(covid['STATUS COVID'] == 'SEDANG'), np.count_nonzero(covid['STATUS COVID'] == 'TINGGI')]
label = ['Covid Rendah', 'Covid Sedang', 'Covid Tinggi']
plt.title('Status Covid')
plt.pie(covidOrno, labels = label, radius=1.3, startangle=60, autopct='%.1f%%', shadow=True)
plt.show()

# mengecek missing values
covid.isna().sum()

# mengisi missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='-')
imputer = imputer.fit(covid[['NO','PUSKESMAS']])
covid[['NO','PUSKESMAS']] = imputer.transform(covid[['NO','PUSKESMAS']])
covid.isna().sum()

print(covid)

covid.info()

# Encoding Categorical Data
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

covid['STATUS COVID'] = label_encoder.fit_transform(covid['STATUS COVID'])
covid['STATUS COVID'].unique()

print(covid)

# menampilkan outlier dengan Box Plot

plt.boxplot(covid['KASUS KONFIRMASI'], vert=False)
plt.ylabel('Variable')
plt.xlabel('Kasus Konfirmasi')
plt.title('Box Plot')

plt.show()

# menampilkan plot dataset

covid.plot(kind = 'bar')

covid

dataset = pd.concat([covid, AQI], axis=1)
print(dataset)

import pandas as pd

# Create a sample DataFrame
data = {
    'Column1': [1, 2, 3],
    'Column2': [4, 5, 6],
    'Column3': [7, 8, 9],
    'Column4': [10, 11, 12],
    'Column5': [13, 14, 15]
}

df = pd.DataFrame(data)

# Pop the column from position 3 (Column3)
column_to_move = df.pop('Column3')

# Insert the popped column at position 5
df.insert(4, 'Column3', column_to_move)

print(df)

dataset['STATUS COVID']
X = dataset.iloc[:,8:20]
print(X)

# K-Means Clustering
X = dataset.iloc[:,8:20]
X = pd.DataFrame(X)
X = X.dropna()
column_to_move = X.pop('STATUS COVID')
X.insert(11, 'STATUS COVID', column_to_move)
print(X)

# Using the elbow method to find the optimal number of clusters
X = X.iloc[:,0:11].values
from sklearn.cluster import KMeans
wcss =[]
for i in range (1,11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter =300, n_init = 10, random_state = 0)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Plot the graph to visualize the Elbow Method to find the optimal number of cluster
plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

# Applying KMeans to the dataset with the optimal number of cluster

kmeans=KMeans(n_clusters= 2, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
Y_Kmeans = kmeans.fit_predict(X)

# Visualising the clusters

plt.scatter(X[Y_Kmeans == 0, 0], X[Y_Kmeans == 0,1],s = 100, c='red', label = 'Cluster 1')

plt.scatter(X[Y_Kmeans == 1, 0], X[Y_Kmeans == 1,1],s = 100, c='blue', label = 'Cluster 2')

#plt.scatter(X[Y_Kmeans == 2, 0], X[Y_Kmeans == 2,1],s = 100, c='green', label = 'Cluster 3')

#plt.scatter(X[Y_Kmeans == 3, 0], X[Y_Kmeans == 3,1],s = 100, c='cyan', label = 'Cluster 4')

#plt.scatter(X[Y_Kmeans == 4, 0], X[Y_Kmeans == 4,1],s = 100, c='magenta', label = 'Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s = 300, c = 'yellow', label = 'Centroids')

plt.title('Clusters of cases')
plt.xlabel('Status Covid')
plt.ylabel('Kualitas Udara')
plt.legend()
plt.show()